[workspace]
members = [
    "rustboyadvance-core/",
    "platform/rustboyadvance-sdl2",
    "platform/rustboyadvance-minifb",
    "platform/rustboyadvance-wasm",
    "bindings/rustboyadvance-jni",
    "fps_bench"
]

[profile.dev]
opt-level = 0
debug = true
