[package]
name = "rustboyadvance-ng"
version = "0.1.0"
authors = ["Michel Heily <michelheily@gmail.com>"]
edition = "2018"
default-run= "rba-sdl2"

[dependencies]
serde = {version = "1.0.104", features = ["derive"] }
bincode = "1.2.1"
byteorder = "1"
num = "0.2.1"
num-traits = "0.2"
enum-primitive-derive = "^0.1"
bit = "^0.1"
clap = {version = "2.33", features = ["color", "yaml"]}
colored = "1.8"
ansi_term = "0.11.0"
hexdump = "0.1.0"
sdl2 = {version = "0.33.0", features = ["image"]}
minifb = "0.11.2"
time = "0.2.6"
bitfield = "0.13.1"
bitflags = "1.2.1"
zip = "0.5.3"
ctrlc = "3.1.3"
spin_sleep="0.3.7"
bit-set = "0.5.1"
ringbuf = "0.2.1"
debug_stub_derive = "0.3.0"
bytesize = "1.0.0"
memmem = "0.1.1"
log = "0.4.8"
flexi_logger = {version = "0.14", features = ["colors"]}
arrayvec = "0.5.1"

rustyline = {version = "6.0.0", optional = true}
nom = {version = "5.0.0", optional = true}

[[bin]]
name = "rba-sdl2"
path = "src/plat/sdl2/main.rs"

[[bin]]
name = "rba-minifb"
path = "src/plat/minifb/main.rs"

[features]
debugger = ["nom", "rustyline"]

[profile.dev]
opt-level = 0
debug = true